
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.FileSystems;
import java.nio.file.Path;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
      public static void main(String[] args) {
          File file = new File(args[0]);
          String transform = args[2];
          try{
              BufferedImage reader = ImageIO.read(file);
              Bitmap image = new Bitmap(reader, args[1]);
              switch (transform.toLowerCase()){
                  case "flipvertical": image.flipVertically();
                  break;
                  case "fliphorizontal": image.flipHorizontally();
                  case "darken": image.darken();
                  default: System.out.println("Please select valid tranform name!!");
              }
              System.out.println("transformation  applied!!!");

          }catch (IOException e){
              System.out.println("opps! something happend make sure you give the correct input arguments");
          }
    }



}
